// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TelegramBotFlow.Broadcasts.Infrastructure;

#nullable disable

namespace TelegramBotFlow.Broadcasts.Infrastructure.Migrations
{
    [DbContext(typeof(BroadcastsDbContext))]
    partial class BroadcastsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.Broadcast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failure_count");

                    b.Property<long>("FromChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_chat_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SuccessCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("success_count");

                    b.HasKey("Id");

                    b.ToTable("broadcasts", (string)null);
                });

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.BroadcastSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("broadcast_sequences", (string)null);
                });

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.BroadcastSequenceStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("DelayAfterJoin")
                        .HasColumnType("interval")
                        .HasColumnName("delay_after_join");

                    b.Property<long>("FromChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_chat_id");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("SequenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sequence_id");

                    b.HasKey("Id");

                    b.HasIndex("SequenceId", "Order")
                        .IsUnique();

                    b.ToTable("broadcast_sequence_steps", (string)null);
                });

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.UserSequenceProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SequenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("sequence_id");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uuid")
                        .HasColumnName("step_id");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("UserId", "SequenceId", "StepId");

                    b.HasIndex("UserId", "SequenceId");

                    b.ToTable("user_sequence_progress", (string)null);
                });

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.BroadcastSequenceStep", b =>
                {
                    b.HasOne("TelegramBotFlow.Broadcasts.Domain.BroadcastSequence", "Sequence")
                        .WithMany("Steps")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("TelegramBotFlow.Broadcasts.Domain.BroadcastSequence", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
